import { relativeTime } from '../../lib/relativeTime'
import { TagChip } from './TagChip'
import { BookmarkIcon, EnvelopeIcon, LinkIcon, SparkleIcon } from '../ui/icons'

export function ArticleCard({
  article,
  summary,
  isBookmarked,
  onToggleBookmark,
  isSelected,
  onToggleSelect,
  onShare,
  onCopyLink,
}) {
  const iconButton =
    'rounded-lg p-1.5 text-gray-400 hover:bg-gray-100 hover:text-gray-700 dark:hover:bg-surface-700 dark:hover:text-gray-200'

  return (
    <article
      className={`group relative rounded-xl border bg-white p-5 transition-colors dark:bg-surface-900 ${
        isSelected
          ? 'border-accent-500 ring-1 ring-accent-500'
          : 'border-gray-200 dark:border-surface-800'
      }`}
    >
      <input
        type="checkbox"
        checked={isSelected}
        onChange={() => onToggleSelect(article.id)}
        aria-label={`Select "${article.title}" for digest`}
        className={`absolute -left-2.5 -top-2.5 size-5 cursor-pointer rounded border-gray-300 accent-accent-600 transition-opacity max-sm:opacity-100 ${
          isSelected ? 'opacity-100' : 'opacity-0 group-hover:opacity-100 focus-visible:opacity-100'
        }`}
      />

      <div className="flex items-center justify-between gap-2">
        <span className="flex min-w-0 items-center gap-2">
          <img src={article.favicon} alt="" className="size-5 shrink-0 rounded" loading="lazy" />
          <span className="truncate text-xs font-semibold text-gray-500 dark:text-gray-400">
            {article.sourceName}
          </span>
        </span>
        <time
          dateTime={article.publishedAt ?? undefined}
          className="shrink-0 text-xs text-gray-400"
        >
          {relativeTime(article.publishedAt)}
        </time>
      </div>

      <h2 className="mt-3 text-base font-bold leading-snug">
        <a
          href={article.url}
          target="_blank"
          rel="noopener noreferrer"
          className="hover:text-accent-500 dark:hover:text-accent-400"
        >
          {article.title}
        </a>
      </h2>

      <p className="mt-2 text-sm leading-relaxed text-gray-600 dark:text-gray-300">
        {summary?.text ?? article.excerpt}
        {summary?.kind === 'ai' && (
          <span
            className="ml-1.5 inline-flex items-center gap-0.5 align-middle text-[10px] font-semibold uppercase tracking-wide text-accent-500 dark:text-accent-400"
            title="Summary generated by AI"
          >
            <SparkleIcon className="size-3" />
            AI
          </span>
        )}
      </p>

      <div className="mt-3 flex flex-wrap items-center gap-1.5">
        {article.tags.map((tagId) => (
          <TagChip key={tagId} tagId={tagId} />
        ))}
      </div>

      <div className="mt-4 flex items-center justify-between">
        <a
          href={article.url}
          target="_blank"
          rel="noopener noreferrer"
          className="text-sm font-semibold text-accent-500 hover:text-accent-600 dark:text-accent-400"
        >
          Read full article →
        </a>
        <div className="flex items-center gap-0.5">
          <button
            type="button"
            onClick={() => onCopyLink(article)}
            aria-label="Copy article link"
            title="Copy link"
            className={iconButton}
          >
            <LinkIcon className="size-4" />
          </button>
          <button
            type="button"
            onClick={() => onShare(article)}
            aria-label="Share via email"
            title="Share via email"
            className={iconButton}
          >
            <EnvelopeIcon className="size-4" />
          </button>
          <button
            type="button"
            onClick={() => onToggleBookmark(article.id)}
            aria-label={isBookmarked ? 'Remove bookmark' : 'Bookmark article'}
            title={isBookmarked ? 'Remove bookmark' : 'Bookmark'}
            aria-pressed={isBookmarked}
            className={`${iconButton} ${isBookmarked ? 'text-accent-500 dark:text-accent-400' : ''}`}
          >
            <BookmarkIcon className="size-4" filled={isBookmarked} />
          </button>
        </div>
      </div>
    </article>
  )
}
